name: Notify
on:
  push:
    branches:
      - main
      - develop
jobs:
  notify:
    uses: iqb-specifications/iqb-specifications.github.io/.github/workflows/reusable_notify.yml@main
    secrets: inherit
